### ISSUE TITLE
Cannot find module './sites'

### ISSUE THREAD

**Issue by gloss-water** [iCrawl/Kaori#1]
When I use kaori by copy/pasting the example from the readme, I get this error:
`Error: Cannot find module './sites'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/Dev/kaoris/node_modules/kaori/src/Kaori.js:6:15)
...etc etc`

Moving sites.json into src/ fixes it for me. I was going to fork/commit/pr etc but I figured I'm doing something wrong / it's not really a new feature
node 7.9.0 / npm 4.2.0

**Comment by iCrawl** [comment]
That is indeed a bug.

**Comment by iCrawl** [comment]
Fixed in 6c495b2a
